#!/usr/bin/env python3
"""Write a SAM3 training config for this CGH pathology package.

Run after cloning and installing facebookresearch/sam3 on the GPU cluster:

    python3 write_sam3_config.py --sam3-repo /path/to/sam3

The script copies the official Roboflow training template into
sam3/train/configs/cgh_pathology/cgh_pathology_sam31_seg.yaml and patches it
for the local COCO dataset generated by prepare_sam31_dataset.py.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parent
DATASET_ROOT = PACKAGE_ROOT / "dataset" / "coco_sam3"
OUTPUT_ROOT = PACKAGE_ROOT / "outputs" / "sam31_runs"

LOSS_TARGET_CANDIDATES = [
    "sam3.train.loss.loss_fns.SemanticSegCriterion",
    "sam3.train.losses.loss_fns.SemanticSegCriterion",
    "sam3.loss.loss_fns.SemanticSegCriterion",
    "sam3.losses.loss_fns.SemanticSegCriterion",
]


def uncomment_yaml_block(block: str) -> str:
    lines = []
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("# NOTE"):
            continue
        if line.startswith("  # "):
            lines.append("  " + line[4:])
        elif line.startswith("  #"):
            lines.append("  " + line[3:])
    return "\n".join(line for line in lines if line.strip())


def build_config(sam3_repo: Path) -> Path:
    template = (
        sam3_repo
        / "sam3"
        / "train"
        / "configs"
        / "roboflow_v100"
        / "roboflow_v100_full_ft_100_images.yaml"
    )
    if not template.exists():
        raise FileNotFoundError(f"SAM3 template config not found: {template}")

    text = template.read_text()
    text = text.replace(
        "roboflow_vl_100_root: <YOUR_DATASET_DIR>",
        f"roboflow_vl_100_root: {DATASET_ROOT}",
    )
    text = text.replace(
        "experiment_log_dir: <YOUR EXPERIMENET LOG_DIR>",
        f"experiment_log_dir: {OUTPUT_ROOT}",
    )
    text = text.replace(
        "bpe_path: <BPE_PATH> # This should be under sam3/assets/bpe_simple_vocab_16e6.txt.gz",
        f"bpe_path: {sam3_repo / 'sam3' / 'assets' / 'bpe_simple_vocab_16e6.txt.gz'}",
    )
    text = text.replace(
        "supercategory: ${all_roboflow_supercategories.${string:${submitit.job_array.task_index}}}",
        "supercategory: cgh_pathology_sam31",
    )
    text = text.replace("num_images: 100", "num_images: null")
    text = text.replace(
        "enable_segmentation: False # NOTE: This is the number of queries used for segmentation",
        "enable_segmentation: True # CGH pathology uses mask supervision",
    )
    text = text.replace("resolution: 1008", "resolution: 1008")
    text = text.replace("num_train_workers: 10", "num_train_workers: 0")
    text = text.replace("num_val_workers: 0", "num_val_workers: 0")
    text = text.replace("max_data_epochs: 20", "max_data_epochs: 50")
    text = text.replace("target_epoch_size: 1500", "target_epoch_size: 1000")
    text = text.replace("\n  max_ann_per_img: 200", "\n  max_ann_per_img: 50")
    text = text.replace("\n        max_ann_per_img: 500000", "\n        max_ann_per_img: 200")
    text = text.replace("\n        max_ann_per_img: 100000", "\n        max_ann_per_img: 200")
    text = text.replace("max_train_queries: 50000", "max_train_queries: 1024")
    text = text.replace("max_val_queries: 50000", "max_val_queries: 1024")
    text = text.replace("amp_dtype: bfloat16", "amp_dtype: float16")
    text = text.replace("skip_saving_ckpts: true", "skip_saving_ckpts: false", 1)
    text = text.replace("max_epochs: 20", "max_epochs: ${scratch.max_data_epochs}", 1)
    text = text.replace("gpus_per_node: 2", "gpus_per_node: 1")
    text = text.replace("  use_cluster: True", "  use_cluster: False")
    text = text.replace("    num_tasks: 100", "    num_tasks: 1")
    text = text.replace(
        "    wandb_writer: null",
        """    wandb_writer:
      _target_: sam3.train.utils.logger.make_wandb_logger
      project: ${oc.env:WANDB_PROJECT,sam31-cgh}
      name: ${oc.env:WANDB_RUN_NAME,cgh_pathology_sam31}
      dir: ${launcher.experiment_log_dir}/wandb
      mode: ${oc.env:WANDB_MODE,online}""",
    )
    text = text.replace(
        """  val_transforms:
    - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
      transforms:
        - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
""",
        """  val_transforms:
    - _target_: sam3.train.transforms.basic_for_api.ComposeAPI
      transforms:
        - _target_: sam3.train.transforms.segmentation.DecodeRle
        - _target_: sam3.train.transforms.basic_for_api.RandomResizeAPI
""",
    )
    loss_target = detect_loss_target(sam3_repo)

    active_start = text.index("  # loss config (no mask loss)")
    seg_note = text.index("  # NOTE: Loss to be used for training in case of segmentation", active_start)
    helper_start = text.index(
        "\n# ============================================================================\n# Different helper parameters",
        seg_note,
    )
    seg_loss = uncomment_yaml_block(text[seg_note:helper_start])
    text = (
        text[:active_start]
        + "  # loss config with mask supervision for pathology segmentation\n"
        + seg_loss
        + text[helper_start:]
    )
    for candidate in LOSS_TARGET_CANDIDATES:
        text = text.replace(candidate, loss_target)

    out_dir = sam3_repo / "sam3" / "train" / "configs" / "cgh_pathology"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "cgh_pathology_sam31_seg.yaml"
    out_path.write_text(text)
    return out_path


def detect_loss_target(sam3_repo: Path) -> str:
    """Return the installed SAM3 SemanticSegCriterion Hydra target.

    SAM3 training package layouts differ between releases/source installs. The
    generated config must point Hydra at the loss module that is actually
    importable on the cluster.
    """
    repo_path = str(sam3_repo.resolve())
    if repo_path not in sys.path:
        sys.path.insert(0, repo_path)
    for candidate in LOSS_TARGET_CANDIDATES:
        module_name, attr_name = candidate.rsplit(".", 1)
        try:
            module = __import__(module_name, fromlist=[attr_name])
            getattr(module, attr_name)
            return candidate
        except Exception:
            continue
    local_matches = sorted((sam3_repo / "sam3").glob("**/loss_fns.py"))
    if local_matches:
        rel = local_matches[0].relative_to(sam3_repo).with_suffix("")
        module_name = ".".join(rel.parts)
        return f"{module_name}.SemanticSegCriterion"
    raise ImportError(
        "Could not locate SemanticSegCriterion in the SAM3 checkout. "
        "Run from the environment where SAM3 is installed, then check: "
        "find SAM3_REPO -name loss_fns.py"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sam3-repo", required=True, type=Path)
    args = parser.parse_args()
    out_path = build_config(args.sam3_repo.resolve())
    print(out_path)


if __name__ == "__main__":
    main()
